using System.Collections.Generic;

namespace SWEN344_Prototype
{
	public class StubQuestions
	{

		public List<Question> questions { get; set; }

		public string subject { get; set; }

		public int grade { get; set; }

		public StubQuestions()
		{
			questions = new List<Question>();

			grade = 0;
			subject = "Math";
			List<Answer> answers = new List<Answer>();
			Answer answer1 = new Answer();
			Answer answer2 = new Answer();
			Answer answer3 = new Answer();
			Answer answer4 = new Answer();

			//questions
			Question one = new Question();
			one.name = " 1 , 2 , 3 ,_?_";
			one.grade = 0;
			one.level = 1;
			one.subject = "Math";
			one.complete = false;
			one.classroom = null;
			one.imageString = "thinking_1";
			answer1.name = "1";
			answer1.points = one.level * 100;
			answer1.correct = false;
			answers.Insert(0, answer1);
			answer2.name = "2";
			answer2.points = one.level * 100;
			answer2.correct = false;
			answers.Insert(1, answer2);
			answer3.name = "3";
			answer3.points = one.level * 100;
			answer3.correct = false;
			answers.Insert(2, answer3);
			answer4.name = "4";
			answer4.points = one.level * 100;
			answer4.correct = true;
			answers.Insert(3, answer4);
			one.answers = answers;
			questions.Add(one);


			List<Answer> answers2 = new List<Answer>();
			answers2.Capacity = 4;
			Answer answer1a = new Answer();
			Answer answer2a = new Answer();
			Answer answer3a = new Answer();
			Answer answer4a = new Answer();
			Question two = new Question();
			two.name = " 4 , 5 , 6 ,_?_";
			two.grade = 0;
			two.level = 1;
			two.subject = "Math";
			two.complete = false;
			two.classroom = null;
			two.imageString = "thinking_2";
			answer1a.name = "1";
			answer1a.points = one.level * 100;
			answer1a.correct = false;
			answers2.Insert(0, answer1a);
			answer2a.name = "2";
			answer2a.points = one.level * 100;
			answer2a.correct = false;
			answers2.Insert(1, answer2a);
			answer3a.name = "3";
			answer3a.points = one.level * 100;
			answer3a.correct = false;
			answers2.Insert(2, answer3a);
			answer4a.name = "7";
			answer4a.points = one.level * 100;
			answer4a.correct = true;
			answers2.Insert(3, answer4a);
			two.answers = answers2;
			questions.Add(two);

			//Question 3
			List<Answer> answers3 = new List<Answer>();
			answers3.Capacity = 4;
			Answer answer1b = new Answer();
			Answer answer2b = new Answer();
			Answer answer3b = new Answer();
			Answer answer4b = new Answer();
			Question three = new Question();
			three.name = " 4 , 3 ,_?_, 1 ";
			three.grade = 0;
			three.level = 1;
			three.subject = "Math";
			three.complete = false;
			three.classroom = null;
			three.imageString = "thinking_3";
			answer1b.name = "3";
			answer1b.points = one.level * 100;
			answer1b.correct = false;
			answers3.Insert(0, answer1b);
			answer2b.name = "2";
			answer2b.points = one.level * 100;
			answer2b.correct = true;
			answers3.Insert(1, answer2b);
			answer3b.name = "1";
			answer3b.points = one.level * 100;
			answer3b.correct = false;
			answers3.Insert(2, answer3b);
			answer4b.name = "10";
			answer4b.points = one.level * 100;
			answer4b.correct = false;
			answers3.Insert(3, answer4b);
			three.answers = answers3;
			questions.Add(three);

			//Question 4
			List<Answer> answers4 = new List<Answer>();
			answers4.Capacity = 4;
			Answer answer1c = new Answer();
			Answer answer2c = new Answer();
			Answer answer3c = new Answer();
			Answer answer4c = new Answer();
			Question four = new Question();
			four.name = "How many Bananas are there?";
			four.grade = 0;
			four.level = 1;
			four.subject = "Math";
			four.complete = false;
			four.classroom = null;
			four.imageString = "4_bananas";
			answer1c.name = "1";
			answer1c.points = one.level * 100;
			answer1c.correct = false;
			answers4.Insert(0, answer1c);
			answer2c.name = "0";
			answer2c.points = one.level * 100;
			answer2c.correct = false;
			answers4.Insert(1, answer2c);
			answer3c.name = "4";
			answer3c.points = one.level * 100;
			answer3c.correct = true;
			answers4.Insert(2, answer3c);
			answer4c.name = "2";
			answer4c.points = one.level * 100;
			answer4c.correct = false;
			answers4.Insert(3, answer4c);
			four.answers = answers4;
			questions.Add(four);

			//Question 5
			List<Answer> answers5 = new List<Answer>();
			answers2.Capacity = 4;
			Answer answer5a = new Answer();
			Answer answer5b = new Answer();
			Answer answer5c = new Answer();
			Answer answer5d = new Answer();
			Question five = new Question();
			five.name = "How many Green Apples are there?";
			five.grade = 0;
			five.level = 1;
			five.subject = "Math";
			five.complete = false;
			five.classroom = null;
			five.imageString = "1_green_apple";
			answer5a.name = "1";
			answer5a.points = one.level * 100;
			answer5a.correct = true;
			answers5.Insert(0, answer5a);
			answer5b.name = "4";
			answer5b.points = one.level * 100;
			answer5b.correct = false;
			answers5.Insert(1, answer5b);
			answer5c.name = "2";
			answer5c.points = one.level * 100;
			answer5c.correct = false;
			answers5.Insert(2, answer5c);
			answer5d.name = "0";
			answer5d.points = one.level * 100;
			answer5d.correct = false;
			answers5.Insert(3, answer5d);
			five.answers = answers5;
			questions.Add(five);

			//Question 6
			List<Answer> answers6 = new List<Answer>();
			answers6.Capacity = 4;
			Answer answer6a = new Answer();
			Answer answer6b = new Answer();
			Answer answer6c = new Answer();
			Answer answer6d = new Answer();
			Question six = new Question();
			six.name = "9 , 8 , 7 ,_?_";
			six.grade = 0;
			six.level = 1;
			six.subject = "Math";
			six.complete = false;
			six.classroom = null;
			six.imageString = "thinking_2";
			answer6a.name = "4";
			answer6a.points = one.level * 100;
			answer6a.correct = false;
			answers6.Insert(0, answer6a);
			answer6b.name = "6";
			answer6b.points = one.level * 100;
			answer6b.correct = true;
			answers6.Insert(1, answer6b);
			answer6c.name = "5";
			answer6c.points = one.level * 100;
			answer6c.correct = false;
			answers6.Insert(2, answer6c);
			answer6d.name = "7";
			answer6d.points = one.level * 100;
			answer6d.correct = false;
			answers6.Insert(3, answer6d);
			six.answers = answers6;
			questions.Add(six);

			//Question 7
			List<Answer> answers7 = new List<Answer>();
			answers7.Capacity = 4;
			Answer answer7a = new Answer();
			Answer answer7b = new Answer();
			Answer answer7c = new Answer();
			Answer answer7d = new Answer();
			Question seven = new Question();
			seven.name = "How many Green Apples are there?";
			seven.grade = 0;
			seven.level = 1;
			seven.subject = "Math";
			seven.complete = false;
			seven.classroom = null;
			seven.imageString = "2_green_apples";
			answer7a.name = "1";
			answer7a.points = one.level * 100;
			answer7a.correct = false;
			answers7.Insert(0, answer7a);
			answer7b.name = "0";
			answer7b.points = one.level * 100;
			answer7b.correct = false;
			answers7.Insert(1, answer7b);
			answer7c.name = "2";
			answer7c.points = one.level * 100;
			answer7c.correct = true;
			answers7.Insert(2, answer7c);
			answer7d.name = "4";
			answer7d.points = one.level * 100;
			answer7d.correct = false;
			answers7.Insert(3, answer7d);
			seven.answers = answers7;
			questions.Add(seven);

			//Question 8
			List<Answer> answers8 = new List<Answer>();
			answers8.Capacity = 4;
			Answer answer8a = new Answer();
			Answer answer8b = new Answer();
			Answer answer8c = new Answer();
			Answer answer8d = new Answer();
			Question eight = new Question();
			eight.name = "How many Bananas are there?";
			eight.level = 1;
			eight.subject = "Math";
			eight.complete = false;
			eight.classroom = null;
			eight.imageString = "3_bananas";
			answer8a.name = "1";
			answer8a.points = one.level * 100;
			answer8a.correct = false;
			answers8.Insert(0, answer8a);
			answer8b.name = "2";
			answer8b.points = one.level * 100;
			answer8b.correct = false;
			answers8.Insert(1, answer8b);
			answer8c.name = "3";
			answer8c.points = one.level * 100;
			answer8c.correct = true;
			answers8.Insert(2, answer8c);
			answer8d.name = "4";
			answer8d.points = one.level * 100;
			answer8d.correct = false;
			answers8.Insert(3, answer8d);
			eight.answers = answers8;
			questions.Add(eight);

			//Question 9
			List<Answer> answers9 = new List<Answer>();
			answers9.Capacity = 4;
			Answer answer9a = new Answer();
			Answer answer9b = new Answer();
			Answer answer9c = new Answer();
			Answer answer9d = new Answer();
			Question nine = new Question();
			nine.name = "How many Bananas are there?";
			nine.grade = 0;
			nine.level = 1;
			nine.subject = "Math";
			nine.complete = false;
			nine.classroom = null;
			nine.imageString = "2_bananas";
			answer9a.name = "2";
			answer9a.points = one.level * 100;
			answer9a.correct = true;
			answers9.Insert(0, answer9a);
			answer9b.name = "0";
			answer9b.points = one.level * 100;
			answer9b.correct = false;
			answers9.Insert(1, answer9b);
			answer9c.name = "3";
			answer9c.points = one.level * 100;
			answer9c.correct = false;
			answers9.Insert(2, answer9c);
			answer9d.name = "1";
			answer9d.points = one.level * 100;
			answer9d.correct = false;
			answers9.Insert(3, answer9d);
			nine.answers = answers9;
			questions.Add(nine);

			//Question 10
			List<Answer> answers10 = new List<Answer>();
			answers2.Capacity = 4;
			Answer answer10a = new Answer();
			Answer answer10b = new Answer();
			Answer answer10c = new Answer();
			Answer answer10d = new Answer();
			Question ten = new Question();
			ten.name = "How many Apples are there?";
			ten.grade = 0;
			ten.level = 2;
			ten.subject = "Math";
			ten.complete = false;
			ten.classroom = null;
			ten.imageString = "fruit_basket";
			answer10a.name = "2";
			answer10a.points = one.level * 100;
			answer10a.correct = false;
			answers10.Insert(0, answer10a);
			answer10b.name = "3";
			answer10b.points = one.level * 100;
			answer10b.correct = false;
			answers10.Insert(1, answer10b);
			answer10c.name = "4";
			answer10c.points = one.level * 100;
			answer10c.correct = true;
			answers10.Insert(2, answer10c);
			answer10d.name = "9";
			answer10d.points = one.level * 100;
			answer10d.correct = false;
			answers10.Insert(3, answer10d);
			ten.answers = answers10;
			questions.Add(ten);

			//Question 11
			List<Answer> answers11 = new List<Answer>();
			answers11.Capacity = 4;
			Answer answer11a = new Answer();
			Answer answer11b = new Answer();
			Answer answer11c = new Answer();
			Answer answer11d = new Answer();
			Question eleven = new Question();
			eleven.name = "1 + 1 = ?";
			eleven.grade = 0;
			eleven.level = 2;
			eleven.subject = "Math";
			eleven.complete = false;
			eleven.classroom = null;
			eleven.imageString = "thinking_3";
			answer11a.name = "1";
			answer11a.points = one.level * 100;
			answer11a.correct = false;
			answers11.Insert(0, answer11a);
			answer11b.name = "2";
			answer11b.points = one.level * 100;
			answer11b.correct = true;
			answers11.Insert(1, answer11b);
			answer11c.name = "3";
			answer11c.points = one.level * 100;
			answer11c.correct = false;
			answers11.Insert(2, answer11c);
			answer11d.name = "4";
			answer11d.points = one.level * 100;
			answer11d.correct = false;
			answers11.Insert(3, answer11d);
			eleven.answers = answers11;
			questions.Add(eleven);

			//Question 12
			List<Answer> answers12 = new List<Answer>();
			answers12.Capacity = 4;
			Answer answer12a = new Answer();
			Answer answer12b = new Answer();
			Answer answer12c = new Answer();
			Answer answer12d = new Answer();
			Question twelve = new Question();
			twelve.name = "3 + 1 = ?";
			twelve.grade = 0;
			twelve.level = 2;
			twelve.subject = "Math";
			twelve.complete = false;
			twelve.classroom = null;
			twelve.imageString = "thinking_4";
			answer12a.name = "1";
			answer12a.points = one.level * 100;
			answer12a.correct = false;
			answers12.Insert(0, answer12a);
			answer12b.name = "2";
			answer12b.points = one.level * 100;
			answer12b.correct = false;
			answers12.Insert(1, answer12b);
			answer12c.name = "3";
			answer12c.points = one.level * 100;
			answer12c.correct = false;
			answers12.Insert(2, answer12c);
			answer12d.name = "4";
			answer12d.points = one.level * 100;
			answer12d.correct = true;
			answers12.Insert(3, answer12d);
			twelve.answers = answers12;
			questions.Add(twelve);

			//Question 13
			List<Answer> answers13 = new List<Answer>();
			answers13.Capacity = 4;
			Answer answer13a = new Answer();
			Answer answer13b = new Answer();
			Answer answer13c = new Answer();
			Answer answer13d = new Answer();
			Question thirteen = new Question();
			thirteen.name = "2 + 2 = ?";
			thirteen.grade = 0;
			thirteen.level = 2;
			thirteen.subject = "Math";
			thirteen.complete = false;
			thirteen.classroom = null;
			thirteen.imageString = "thinking_1";
			answer13a.name = "1";
			answer13a.points = one.level * 100;
			answer13a.correct = false;
			answers13.Insert(0, answer13a);
			answer13b.name = "2";
			answer13b.points = one.level * 100;
			answer13b.correct = false;
			answers13.Insert(1, answer13b);
			answer13c.name = "3";
			answer13c.points = one.level * 100;
			answer13c.correct = false;
			answers13.Insert(2, answer13c);
			answer13d.name = "4";
			answer13d.points = one.level * 100;
			answer13d.correct = true;
			answers13.Insert(3, answer13d);
			thirteen.answers = answers13;
			questions.Add(thirteen);

			//Question 14
			List<Answer> answers14 = new List<Answer>();
			answers14.Capacity = 4;
			Answer answer14a = new Answer();
			Answer answer14b = new Answer();
			Answer answer14c = new Answer();
			Answer answer14d = new Answer();
			Question fourteen = new Question();
			fourteen.name = "2 + 6 = ?";
			fourteen.grade = 0;
			fourteen.level = 2;
			fourteen.subject = "Math";
			fourteen.complete = false;
			fourteen.classroom = null;
			fourteen.imageString = "thinking_2";
			answer14a.name = "8";
			answer14a.points = one.level * 100;
			answer14a.correct = true;
			answers14.Insert(0, answer14a);
			answer14b.name = "9";
			answer14b.points = one.level * 100;
			answer14b.correct = false;
			answers14.Insert(1, answer14b);
			answer14c.name = "6";
			answer14c.points = one.level * 100;
			answer14c.correct = false;
			answers14.Insert(2, answer14c);
			answer14d.name = "7";
			answer14d.points = one.level * 100;
			answer14d.correct = false;
			answers14.Insert(3, answer14d);
			fourteen.answers = answers14;
			questions.Add(fourteen);

			//Question 15
			List<Answer> answers15 = new List<Answer>();
			answers15.Capacity = 4;
			Answer answer15a = new Answer();
			Answer answer15b = new Answer();
			Answer answer15c = new Answer();
			Answer answer15d = new Answer();
			Question fifteen = new Question();
			fifteen.name = "3 + 2 + 1 = ?";
			fifteen.grade = 0;
			fifteen.level = 2;
			fifteen.subject = "Math";
			fifteen.complete = false;
			fifteen.classroom = null;
			fifteen.imageString = "thinking_3";
			answer15a.name = "3";
			answer15a.points = one.level * 100;
			answer15a.correct = false;
			answers15.Insert(0, answer15a);
			answer15b.name = "5";
			answer15b.points = one.level * 100;
			answer15b.correct = false;
			answers15.Insert(1, answer15b);
			answer15c.name = "6";
			answer15c.points = one.level * 100;
			answer15c.correct = true;
			answers15.Insert(2, answer15c);
			answer15d.name = "7";
			answer15d.points = one.level * 100;
			answer15d.correct = false;
			answers15.Insert(3, answer15d);
			fifteen.answers = answers15;
			questions.Add(fifteen);

			//Question 16
			List<Answer> answers16 = new List<Answer>();
			answers16.Capacity = 4;
			Answer answer16a = new Answer();
			Answer answer16b = new Answer();
			Answer answer16c = new Answer();
			Answer answer16d = new Answer();
			Question sixteen = new Question();
			sixteen.name = "9 + 1 = ?";
			sixteen.grade = 0;
			sixteen.level = 2;
			sixteen.subject = "Math";
			sixteen.complete = false;
			sixteen.classroom = null;
			sixteen.imageString = "thinking_4";
			answer16a.name = "1";
			answer16a.points = one.level * 100;
			answer16a.correct = false;
			answers16.Insert(0, answer16a);
			answer16b.name = "0";
			answer16b.points = one.level * 100;
			answer16b.correct = false;
			answers16.Insert(1, answer16b);
			answer16c.name = "9";
			answer16c.points = one.level * 100;
			answer16c.correct = false;
			answers16.Insert(2, answer16c);
			answer16d.name = "10";
			answer16d.points = one.level * 100;
			answer16d.correct = true;
			answers16.Insert(3, answer16d);
			sixteen.answers = answers16;
			questions.Add(sixteen);

			//Question 17
			List<Answer> answers17 = new List<Answer>();
			answers17.Capacity = 4;
			Answer answer17a = new Answer();
			Answer answer17b = new Answer();
			Answer answer17c = new Answer();
			Answer answer17d = new Answer();
			Question seventeen = new Question();
			seventeen.name = "4 + 3";
			seventeen.grade = 0;
			seventeen.level = 2;
			seventeen.subject = "Math";
			seventeen.complete = false;
			seventeen.classroom = null;
			seventeen.imageString = "thinking_1";
			answer17a.name = "10";
			answer17a.points = one.level * 100;
			answer17a.correct = false;
			answers17.Insert(0, answer17a);
			answer17b.name = "7";
			answer17b.points = one.level * 100;
			answer17b.correct = true;
			answers17.Insert(1, answer17b);
			answer17c.name = "3";
			answer17c.points = one.level * 100;
			answer17c.correct = false;
			answers17.Insert(2, answer17c);
			answer17d.name = "6";
			answer17d.points = one.level * 100;
			answer17d.correct = false;
			answers17.Insert(3, answer17d);
			seventeen.answers = answers17;
			questions.Add(seventeen);

			//Question 18
			List<Answer> answers18 = new List<Answer>();
			answers2.Capacity = 4;
			Answer answer18a = new Answer();
			Answer answer18b = new Answer();
			Answer answer18c = new Answer();
			Answer answer18d = new Answer();
			Question eighteen = new Question();
			eighteen.name = "6 + 4 = ?";
			eighteen.grade = 0;
			eighteen.level = 2;
			eighteen.subject = "Math";
			eighteen.complete = false;
			eighteen.classroom = null;
			eighteen.imageString = "thinking_2";
			answer18a.name = "10";
			answer18a.points = one.level * 100;
			answer18a.correct = true;
			answers18.Insert(0, answer18a);
			answer18b.name = "2";
			answer18b.points = one.level * 100;
			answer18b.correct = false;
			answers18.Insert(1, answer18b);
			answer18c.name = "5";
			answer18c.points = one.level * 100;
			answer18c.correct = false;
			answers18.Insert(2, answer3a);
			answer18d.name = "9";
			answer18d.points = one.level * 100;
			answer18d.correct = false;
			answers18.Insert(3, answer18d);
			eighteen.answers = answers18;
			questions.Add(eighteen);

			//Question 19
			List<Answer> answers19 = new List<Answer>();
			answers2.Capacity = 4;
			Answer answer19a = new Answer();
			Answer answer19b = new Answer();
			Answer answer19c = new Answer();
			Answer answer19d = new Answer();
			Question nineteen = new Question();
			nineteen.name = "5 + 4 = ?";
			nineteen.grade = 0;
			nineteen.level = 2;
			nineteen.subject = "Math";
			nineteen.complete = false;
			nineteen.classroom = null;
			nineteen.imageString = "thinking_3";
			answer19a.name = "10";
			answer19a.points = one.level * 100;
			answer19a.correct = false;
			answers19.Insert(0, answer19a);
			answer19b.name = "2";
			answer19b.points = one.level * 100;
			answer19b.correct = false;
			answers19.Insert(1, answer19b);
			answer19c.name = "9";
			answer19c.points = one.level * 100;
			answer19c.correct = true;
			answers19.Insert(2, answer19c);
			answer19d.name = "7";
			answer19d.points = one.level * 100;
			answer19d.correct = false;
			answers19.Insert(3, answer19d);
			nineteen.answers = answers19;
			questions.Add(nineteen);

			//Question 20
			List<Answer> answers20 = new List<Answer>();
			answers20.Capacity = 4;
			Answer answer20a = new Answer();
			Answer answer20b = new Answer();
			Answer answer20c = new Answer();
			Answer answer20d = new Answer();
			Question twenty = new Question();
			twenty.name = "1 + 0 = ?";
			twenty.grade = 0;
			twenty.level = 2;
			twenty.subject = "Math";
			twenty.complete = false;
			twenty.classroom = null;
			twenty.imageString = "thinking_4";
			answer20a.name = "1";
			answer20a.points = one.level * 100;
			answer20a.correct = true;
			answers20.Insert(0, answer20a);
			answer20b.name = "0";
			answer20b.points = one.level * 100;
			answer20b.correct = false;
			answers20.Insert(1, answer20b);
			answer20c.name = "10";
			answer20c.points = one.level * 100;
			answer20c.correct = false;
			answers20.Insert(2, answer20c);
			answer20d.name = "2";
			answer20d.points = one.level * 100;
			answer20d.correct = false;
			answers20.Insert(3, answer20d);
			twenty.answers = answers20;
			questions.Add(twenty);
		}
	}
}
